/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Gaiza;
import AdminCommands.*;
import org.javacord.api.DiscordApi;
import org.javacord.api.DiscordApiBuilder;

import UserCommands.*;
import de.btobastian.sdcf4j.CommandHandler;
import de.btobastian.sdcf4j.handler.JavacordHandler;
import Database.*;
import Management.*;
import Listener.*;

import java.io.*;
import java.lang.reflect.Constructor;
import java.util.*;

public class Library
{
	 public boolean someLibraryMethod() {
	        return true;
	 }

	public static void main(String[] args) throws Exception {
		DiscordApi api = new DiscordApiBuilder().setToken(new Token().getToken()).login().join();
		commandInit(api);
	}
	
	@SuppressWarnings("unused")
	static void commandInit(DiscordApi api) throws Exception {
		InitDatabase dbInit = new InitDatabase(api);
		GlobalUserInformation initUsers = new GlobalUserInformation(api);

		System.out.println("\n--------------------------------");
		System.out.println("Bot command files loading... \n");

		Map<String, File> commands = new HashMap();
		commands.put("UserCommands", new File("C:\\Users\\17244\\Documents\\JavaProjects\\Gaiza\\src\\main\\java\\UserCommands\\"));
		commands.put("AdminCommands", new File("C:\\Users\\17244\\Documents\\JavaProjects\\Gaiza\\src\\main\\java\\AdminCommands\\"));
		commands.put("Listener", new File("C:\\Users\\17244\\Documents\\JavaProjects\\Gaiza\\src\\main\\java\\Listener\\"));

		try {
			for (Map.Entry<String, File> command : commands.entrySet()) {
				for (final File commandName : command.getValue().listFiles()) {
					if (!commandName.isDirectory()) {
						Class.forName(command.getKey() + "." + commandName.getName().replace(".java", ""))
								.getDeclaredConstructor(DiscordApi.class).newInstance(api);
						System.out.println(commandName.getName() + " loaded!");
					}
				}
				System.out.println("\n" + command.getKey() + " files loaded!");
				System.out.println("--------------------------------\n");
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		BotInfo bInfoInit = new BotInfo(api);
		System.out.println("Management files loaded!\n");

		api.updateActivity(BotInfo.getBotActivity());
	}
}