/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Gaiza;
import lombok.SneakyThrows;
import org.javacord.api.DiscordApi;
import org.javacord.api.DiscordApiBuilder;

import Database.*;
import Management.*;
import org.javacord.api.entity.intent.Intent;

import java.io.*;
import java.util.*;

public class Library {

	public static void main(String[] args) {
		DiscordApi api = new DiscordApiBuilder().setToken(new Token().getToken()).addIntents(Intent.MESSAGE_CONTENT).login().join();
		commandInit(api);
	}
	
	@SuppressWarnings("unused")
	@SneakyThrows
	static void commandInit(DiscordApi api) {
		BotInfo bInfoInit = new BotInfo(api);
		InitDatabase dbInit = new InitDatabase(api);
		GlobalUserInformation initUsers = new GlobalUserInformation(api);
		SeriesTrackerInformation seriesTracker = new SeriesTrackerInformation();
		api.updateActivity(BotInfo.getBotActivity());

		System.out.println("\n\nManagement files loaded!");
		System.out.println("--------------------------------\n");

		Map<String, File> commands = new HashMap();
//		commands.put("UserCommands", new File("/home/kanra/projects/Gaiza/src/main/java/UserCommands"));
//		commands.put("AdminCommands", new File("/home/kanra/projects/Gaiza/src/main/java/AdminCommands"));
//		commands.put("Listener", new File("/home/kanra/projects/Gaiza/src/main/java/Listener"));
//		commands.put("UserMentions", new File("/home/kanra/projects/Gaiza/src/main/java/UserMentions"));

		commands.put("UserCommands", new File("C:\\Users\\joelm\\IdeaProjects\\Gaiza\\src\\main\\java\\UserCommands"));
		commands.put("AdminCommands", new File("C:\\Users\\joelm\\IdeaProjects\\Gaiza\\src\\main\\java\\AdminCommands"));
		commands.put("Listener", new File("C:\\Users\\joelm\\IdeaProjects\\Gaiza\\src\\main\\java\\Listener"));
		commands.put("UserMentions", new File("C:\\Users\\joelm\\IdeaProjects\\Gaiza\\src\\main\\java\\UserMentions"));


		for (Map.Entry<String, File> command : commands.entrySet()) {
			for (final File commandName : command.getValue().listFiles()) {
				if (!commandName.isDirectory()) {
					Class.forName(command.getKey() + "." + commandName.getName().replace(".java", ""))
							.getDeclaredConstructor(DiscordApi.class).newInstance(api);
					System.out.println(commandName.getName() + " loaded!");
				}
			}
			System.out.println("\n" + command.getKey() + " files loaded!");
			System.out.println("--------------------------------\n");
		}
	}
}